import jwt from 'jsonwebtoken';
import User from '../models/userModel.js';
import sequelize from '../config/db.js';
import { generateRandomPassword } from '../utils/generatePassword.js';
import nodemailer from 'nodemailer';

const JWT_SECRET = process.env.JWT_SECRET || 'tu_clave_secreta_super_segura_cambiala_en_produccion';
const JWT_EXPIRES_IN = process.env.JWT_EXPIRES_IN || '24h';

// Generar token JWT
const generateToken = (userId) => {
  return jwt.sign({ id: userId }, JWT_SECRET, { expiresIn: JWT_EXPIRES_IN });
};

// Registro de usuario
export const register = async (req, res) => {
  try {
    const { Nombres, Apellidos, Correo_Electronico, Contraseña, rol_id } = req.body;

    // Validaciones
    if (!Correo_Electronico) {
      return res.status(400).json({ 
        error: 'El campo Correo_Electronico es obligatorio.' 
      });
    }

    // Si no se proporciona contraseña, generar una aleatoria
    let passwordToUse = Contraseña;
    let isAutoGeneratedPassword = false;
    
    if (!Contraseña) {
      passwordToUse = generateRandomPassword(12);
      isAutoGeneratedPassword = true;
    } else if (Contraseña.length < 6) {
      return res.status(400).json({ 
        error: 'La contraseña debe tener al menos 6 caracteres.' 
      });
    }

    // Verificar si el usuario ya existe
    const existingUser = await User.findOne({ 
      where: { Correo_Electronico } 
    });

    if (existingUser) {
      return res.status(400).json({ 
        error: 'El correo electrónico ya está registrado.' 
      });
    }

    // Crear el usuario
    const newUser = await User.create({
      Nombres: Nombres || null,
      Apellidos: Apellidos || null,
      Correo_Electronico,
      Contraseña: passwordToUse,
      Status: 1,
    });

    // Si la contraseña fue generada automáticamente, enviar correo
    if (isAutoGeneratedPassword) {
      const userName = Nombres || Correo_Electronico.split('@')[0];
      
      // Configurar transporter de Gmail
      const transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
          user: process.env.EMAIL_USER,
          pass: process.env.EMAIL_PASS
        }
      });

      // Configurar el email
      const mailOptions = {
        from: `"TCA - Acervo Bibliográfico" <${process.env.EMAIL_USER}>`,
        to: Correo_Electronico,
        subject: 'Bienvenido - Tu cuenta ha sido creada',
        text: `Hola ${userName}, tu cuenta ha sido creada exitosamente. Tu contraseña temporal es: ${passwordToUse}`,
        html: `
          <!DOCTYPE html>
          <html>
          <head>
            <style>
              body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
              .container { max-width: 600px; margin: 0 auto; padding: 20px; }
              .header { background-color: #801530; color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0; }
              .content { background-color: #f9f9f9; padding: 30px; border: 1px solid #ddd; border-radius: 0 0 8px 8px; }
              .password-box { background-color: #fff; border: 2px solid #801530; padding: 20px; margin: 20px 0; text-align: center; border-radius: 8px; }
              .password { font-size: 24px; font-weight: bold; letter-spacing: 2px; color: #801530; font-family: 'Courier New', monospace; }
              .footer { margin-top: 20px; text-align: center; font-size: 12px; color: #666; }
              .warning { background-color: #fff3cd; border-left: 4px solid #ffc107; padding: 10px; margin: 15px 0; color: #856404; }
            </style>
          </head>
          <body>
            <div class="container">
              <div class="header">
                <h1>¡Bienvenido a TCA!</h1>
              </div>
              <div class="content">
                <p>Hola <strong>${userName}</strong>,</p>
                <p>Tu cuenta ha sido creada exitosamente en nuestro sistema.</p>
                <p>Tu contraseña temporal es:</p>
                <div class="password-box">
                  <div class="password">${passwordToUse}</div>
                </div>
                <div class="warning">
                  <strong>⚠️ Importante:</strong> Por seguridad, te recomendamos cambiar esta contraseña después de iniciar sesión por primera vez.
                </div>
                <p>Puedes iniciar sesión usando tu correo electrónico y esta contraseña.</p>
              </div>
              <div class="footer">
                <hr>
                <p>Si no solicitaste esta cuenta, por favor ignora este correo.</p>
                <p><strong>TCA - Sistema de Acervo Bibliográfico</strong></p>
                <p>📧 ${process.env.EMAIL_USER}</p>
              </div>
            </div>
          </body>
          </html>
        `
      };

      // Enviar el email
      try {
        const info = await transporter.sendMail(mailOptions);
        console.log('='.repeat(50));
        console.log('✅ EMAIL DE REGISTRO ENVIADO');
        console.log('='.repeat(50));
        console.log(`Usuario: ${userName}`);
        console.log(`Email: ${Correo_Electronico}`);
        console.log(`Message ID: ${info.messageId}`);
        console.log('='.repeat(50));
      } catch (emailError) {
        console.error('❌ Error al enviar email de registro:', emailError);
        // No falla el registro si el email no se envía
      }
    }

    // Si se proporcionó un rol_id, asignarlo al usuario
    if (rol_id) {
      await sequelize.query(`
        INSERT INTO rolUsuarios (usuario_id, rol_id, asignado_por, asignado_en)
        VALUES (:usuario_id, :rol_id, NULL, NOW())
      `, {
        replacements: { 
          usuario_id: newUser.Id, 
          rol_id: rol_id 
        },
        type: sequelize.QueryTypes.INSERT,
      });
    }

    // Obtener los roles del usuario
    const roles = await sequelize.query(`
      SELECT r.id, r.nombre, r.slug, r.descripcion
      FROM roles r
      JOIN rolUsuarios ru ON r.id = ru.rol_id
      WHERE ru.usuario_id = :usuario_id
    `, {
      replacements: { usuario_id: newUser.Id },
      type: sequelize.QueryTypes.SELECT,
    });

    // Generar token
    const token = generateToken(newUser.Id);

    res.status(201).json({
      message: isAutoGeneratedPassword 
        ? 'Usuario registrado exitosamente. Se ha enviado la contraseña temporal por correo.' 
        : 'Usuario registrado exitosamente',
      emailSent: isAutoGeneratedPassword,
      token,
      user: {
        Id: newUser.Id,
        Nombres: newUser.Nombres,
        Apellidos: newUser.Apellidos,
        Correo_Electronico: newUser.Correo_Electronico,
        Status: newUser.Status,
        roles: roles.map(r => ({
          id: r.id,
          nombre: r.nombre,
          slug: r.slug,
          descripcion: r.descripcion
        })),
        roleSlugs: roles.map(r => r.slug),
      },
    });
  } catch (error) {
    res.status(500).json({ error: `Error al registrar usuario: ${error.message}` });
  }
};

// Login de usuario
export const login = async (req, res) => {
  try {
    const { Correo_Electronico, Contraseña } = req.body;

    // Validaciones
    if (!Correo_Electronico || !Contraseña) {
      return res.status(400).json({ 
        error: 'Correo_Electronico y Contraseña son obligatorios.' 
      });
    }

    // Buscar usuario por email
    const user = await User.findOne({ 
      where: { Correo_Electronico } 
    });

    if (!user) {
      return res.status(401).json({ 
        error: 'Credenciales inválidas.' 
      });
    }

    if (user.Status !== 1) {
      return res.status(401).json({ 
        error: 'Usuario inactivo. Contacta al administrador.' 
      });
    }

    // Verificar contraseña
    const isPasswordValid = await user.comparePassword(Contraseña);

    if (!isPasswordValid) {
      return res.status(401).json({ 
        error: 'Credenciales inválidas.' 
      });
    }

    // Obtener los roles del usuario
    const roles = await sequelize.query(`
      SELECT r.id, r.nombre, r.slug, r.descripcion
      FROM roles r
      JOIN rolUsuarios ru ON r.id = ru.rol_id
      WHERE ru.usuario_id = :usuario_id
    `, {
      replacements: { usuario_id: user.Id },
      type: sequelize.QueryTypes.SELECT,
    });

    // Generar token
    const token = generateToken(user.Id);

    res.status(200).json({
      message: 'Login exitoso',
      token,
      user: {
        Id: user.Id,
        Nombres: user.Nombres,
        Apellidos: user.Apellidos,
        Correo_Electronico: user.Correo_Electronico,
        Status: user.Status,
        roles: roles.map(r => ({
          id: r.id,
          nombre: r.nombre,
          slug: r.slug,
          descripcion: r.descripcion
        })),
        roleSlugs: roles.map(r => r.slug),
      },
    });
  } catch (error) {
    res.status(500).json({ error: `Error al iniciar sesión: ${error.message}` });
  }
};

// Obtener perfil del usuario autenticado
export const getProfile = async (req, res) => {
  try {
    const user = await User.findByPk(req.user.id, {
      attributes: { exclude: ['Contraseña'] },
    });

    if (!user) {
      return res.status(404).json({ error: 'Usuario no encontrado.' });
    }

    res.status(200).json({
      message: 'Perfil obtenido exitosamente',
      user: {
        ...user.toJSON(),
        roles: req.user.roles || [],
        roleSlugs: req.user.roleSlugs || [],
      },
    });
  } catch (error) {
    res.status(500).json({ error: `Error al obtener perfil: ${error.message}` });
  }
};

// Verificar token
export const verifyToken = async (req, res) => {
  try {
    res.status(200).json({
      message: 'Token válido',
      user: req.user,
    });
  } catch (error) {
    res.status(500).json({ error: `Error al verificar token: ${error.message}` });
  }
};

// Obtener todos los usuarios con paginación
export const getAllUsers = async (req, res) => {
  try {
    const { page = 1, limit = 10, column, value } = req.query;
    const offset = (page - 1) * limit;
    
    let where = {};
    
    // Búsqueda por columna específica
    if (column && value) {
      const { Op } = await import('sequelize');
      
      switch (column) {
        case 'Nombres':
        case 'Nombre(s)':
          where.Nombres = { [Op.like]: `${value}%` };
          break;
        case 'Apellidos':
        case 'Apellido(s)':
          where.Apellidos = { [Op.like]: `${value}%` };
          break;
        case 'Correo_Electronico':
          where.Correo_Electronico = { [Op.like]: `${value}%` };
          break;
        case 'Status':
          const statusValue = value === 'Activo' || value === '1' ? 1 : 0;
          where.Status = statusValue;
          break;
        case 'Rol':
        case 'rol':
          // Búsqueda por rol - necesitaremos hacer un JOIN con rolUsuarios y roles
          // Por ahora, lo dejamos preparado para futura implementación
          break;
        default:
          break;
      }
    }

    const { count, rows } = await User.findAndCountAll({
      where,
      attributes: { exclude: ['Contraseña'] },
      offset: parseInt(offset),
      limit: parseInt(limit),
      order: [['Id', 'ASC']],
    });

    const totalPages = Math.ceil(count / limit);

    res.status(200).json({
      message: 'Usuarios obtenidos exitosamente',
      users: rows,
      pagination: {
        currentPage: parseInt(page),
        totalPages,
        totalItems: count,
        itemsPerPage: parseInt(limit),
      },
    });
  } catch (error) {
    res.status(500).json({ error: `Error al obtener usuarios: ${error.message}` });
  }
};

// Cambiar contraseña
export const changePassword = async (req, res) => {
  try {
    const { Contraseña, Nueva_Contraseña, Confirmar_Contraseña } = req.body;

    // Validaciones
    if (!Contraseña || !Nueva_Contraseña || !Confirmar_Contraseña) {
      return res.status(400).json({ 
        error: 'Todos los campos son obligatorios.' 
      });
    }

    // Validar longitud de la nueva contraseña
    if (Nueva_Contraseña.length < 8) {
      return res.status(400).json({ 
        error: 'La nueva contraseña debe tener al menos 8 caracteres.' 
      });
    }
    const passwordPattern = /(?=.*[a-z])(?=.*[A-Z])(?=.*\d)/;
    if (!passwordPattern.test(Nueva_Contraseña)) {
      return res.status(400).json({
        error: 'La nueva contraseña debe contener al menos una letra mayúscula, una letra minúscula y un número.'
      });
    }

    // Verificar que las contraseñas nuevas coincidan
    if (Nueva_Contraseña !== Confirmar_Contraseña) {
      return res.status(400).json({ 
        error: 'La nueva contraseña y la confirmación no coinciden.' 
      });
    }

    // Verificar que la nueva contraseña sea diferente de la actual
    if (Contraseña === Nueva_Contraseña) {
      return res.status(400).json({ 
        error: 'La nueva contraseña debe ser diferente de la actual.' 
      });
    }

    // Buscar usuario (req.user viene del middleware de autenticación)
    const user = await User.findByPk(req.user.id);

    if (!user) {
      return res.status(404).json({ 
        error: 'Usuario no encontrado.' 
      });
    }

    // Verificar la contraseña actual
    const isPasswordValid = await user.comparePassword(Contraseña);

    if (!isPasswordValid) {
      return res.status(401).json({ 
        error: 'La contraseña actual es incorrecta.' 
      });
    }

    // Actualizar la contraseña (el hook beforeUpdate hasheará automáticamente)
    user.Contraseña = Nueva_Contraseña;
    await user.save();

    res.status(200).json({
      message: 'Contraseña actualizada exitosamente',
    });
  } catch (error) {
    res.status(500).json({ error: `Error al cambiar contraseña: ${error.message}` });
  }
};

// Desactivar usuario (cambiar Status a 0/false)
export const deactivateUser = async (req, res) => {
  try {
    const { id } = req.params;

    // Validar que el ID sea un número entero
    if (!id || isNaN(id) || !Number.isInteger(Number(id))) {
      return res.status(400).json({ error: 'El ID debe ser un número entero válido.' });
    }

    // Buscar usuario por ID
    const user = await User.findByPk(id);

    if (!user) {
      return res.status(404).json({ 
        error: 'Usuario no encontrado.' 
      });
    }

    // Verificar si el usuario ya está desactivado
    if (user.Status === 0 || user.Status === false) {
      return res.status(400).json({ 
        error: 'El usuario ya está desactivado.' 
      });
    }

    // Cambiar Status a 0/false
    user.Status = 0;
    await user.save();

    res.status(200).json({
      message: 'Usuario desactivado exitosamente',
      user: {
        Id: user.Id,
        Nombres: user.Nombres,
        Apellidos: user.Apellidos,
        Correo_Electronico: user.Correo_Electronico,
        Status: user.Status,
      },
    });
  } catch (error) {
    res.status(500).json({ error: `Error al desactivar usuario: ${error.message}` });
  }
};

// Restaurar usuario (cambiar Status a 1/true)
export const restoreUser = async (req, res) => {
  try {
    const { id } = req.params;

    // Validar que el ID sea un número entero
    if (!id || isNaN(id) || !Number.isInteger(Number(id))) {
      return res.status(400).json({ error: 'El ID debe ser un número entero válido.' });
    }

    // Buscar usuario por ID
    const user = await User.findByPk(id);

    if (!user) {
      return res.status(404).json({ 
        error: 'Usuario no encontrado.' 
      });
    }

    // Verificar si el usuario ya está activo
    if (user.Status === 1 || user.Status === true) {
      return res.status(400).json({ 
        error: 'El usuario ya está activo.' 
      });
    }

    // Cambiar Status a 1/true
    user.Status = 1;
    await user.save();

    res.status(200).json({
      message: 'Usuario restaurado exitosamente',
      user: {
        Id: user.Id,
        Nombres: user.Nombres,
        Apellidos: user.Apellidos,
        Correo_Electronico: user.Correo_Electronico,
        Status: user.Status,
      },
    });
  } catch (error) {
    res.status(500).json({ error: `Error al restaurar usuario: ${error.message}` });
  }
};

// Obtener usuario por ID (protegido)
export const getUserById = async (req, res) => {
  try {
    const { id } = req.params;

    // Validar que el ID sea un número entero
    if (!id || isNaN(id) || !Number.isInteger(Number(id))) {
      return res.status(400).json({ error: 'El ID debe ser un número entero válido.' });
    }

    // Buscar usuario por ID excluyendo la contraseña
    const user = await User.findByPk(id, {
      attributes: { exclude: ['Contraseña'] },
    });

    if (!user) {
      return res.status(404).json({ 
        error: 'Usuario no encontrado.' 
      });
    }

    // Obtener los roles del usuario
    const roles = await sequelize.query(`
      SELECT r.id, r.nombre, r.slug, r.descripcion, ru.asignado_en
      FROM roles r
      JOIN rolUsuarios ru ON r.id = ru.rol_id
      WHERE ru.usuario_id = :usuario_id
    `, {
      replacements: { usuario_id: id },
      type: sequelize.QueryTypes.SELECT,
    });

    res.status(200).json({
      message: 'Usuario obtenido exitosamente',
      user: {
        ...user.toJSON(),
        roles: roles.map(r => ({
          id: r.id,
          nombre: r.nombre,
          slug: r.slug,
          descripcion: r.descripcion,
          asignado_en: r.asignado_en
        })),
        roleSlugs: roles.map(r => r.slug),
      },
    });
  } catch (error) {
    res.status(500).json({ error: `Error al obtener usuario: ${error.message}` });
  }
};

export default { register, login, getProfile, verifyToken, changePassword, getAllUsers, deactivateUser, restoreUser, getUserById };
